### ISSUE TITLE
Examples not built

### ISSUE THREAD

**Issue by theoturner** [fetchai/ledger-archive#43]
Some examples are not built with make, e.g. network/quick_start as suggested by the network section of the docs.

**Comment by n-hutton** [comment]
Hi Theo,

Thanks for pointing this out. As it happens, that example is built, but the name has changed to 'example_quick_start', which isn't reflected in the docs. You should be able to build it with `make example_quick_start`. I'll be sure to update the network docs for the next  public push.

Nathan
