### ISSUE TITLE
Issues on make -j with memory consumption

### ISSUE THREAD

**Issue by bpetridis** [fetchai/ledger-archive#49]
Hi need some help,

Following the instructions to do  a local build on an ubuntu 19.04 desktop with 8 cores and 16GB ram. Followed the notes to the letter but when I get to the following step the compilation process, my memory consumption hits 100% almost instantly and the build and desktop come to a grinding halt. I end up having to bounce the machine. Was just wondering if anyone else has had the same issues and whether they have any tips that can help?

make-j

This seems to occur when make hits this C++ file libs/ml/tests/CMakeFiles/ml_ops_gtest.dr/ml/ops/tanh.cpp.o

Cheers

Bill

**Comment by ejfitzgerald** [comment]
Hi Bill,

Sorry to hear you are having troubles. We have occasionally seen this sort of thing too. My best advise would be to specify the number of tasks you want to make in parallel. i.e. if you run the following:

`make -j 4 constellation`

The current build process can be quite expensive (in turns of memory) so this should limit it to only 4 concurrent instances.

Hope that helps,

Ed

**Comment by bpetridis** [comment]
Aaaand - that worked just fine - much appreciated. Mate that's some quick turnaround on support right there, you guys rock, keep up the good work 👍 👍

**Comment by bpetridis** [comment]
Got the answer and it helped a lot - great stuff
